const actionTypes = {
    GET_HOME: 'GET_HOME',
    LOADING: 'LOADING',
    PLAYING_BAR: 'PLAYING_BAR',
    CURRENT_WIDTH: 'CURRENT_WIDTH',

    // music
    SET_CUR_SONG_ID: 'SET_CUR_SONG_ID',
    SET_CUR_SONG_DATA: 'SET_CUR_SONG_DATA',
    SET_CUR_ALBUM_DATA: 'SET_CUR_ALBUM_DATA',
    SET_RECENT: 'SET_RECENT',
    PLAY: 'PLAY',
    VIPSONG: 'VIPSONG',
    PLAYLIST: 'PLAYLIST',
    ARTISTLSONG: 'ARTISTLSONG',

    // search
    SEARCH: 'SEARCH',
}

export default actionTypes
